CREATE TABLE DEPARTAMENTO(
	ID_DEPARTAMENTO INT PRIMARY KEY IDENTITY (1,1),
	NOMBRE_DEPARTAMENTO VARCHAR(100)
);

CREATE TABLE EMPLEADOS(
	ID_EMPLEADO INT PRIMARY KEY IDENTITY (1,1),
	NOMBRE_EMPLEADO VARCHAR(200),
	APELLIDO_EMPLEADO VARCHAR(200),
	DNI INT,
	TELEFONO int,
	DIRECCION VARCHAR(200),
	FECHA_NACIMIENTO DATE, 
	SUELDO BIGINT,
	ID_DEPARTAMENTO INT,
);

ALTER TABLE EMPLEADOS ADD FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTO(ID_DEPARTAMENTO)

